Recette boudoirs
recettes-recipes/blog pull request #4
Opened 2019-11-21 21:48 UTC by Mesh33

Recette pour les boudoirs. Ai-je un moyen de resize l'image avant la génération du code ?

2019-11-21 23:30 UTC, Antoine38660 requested changes
Recette vraiment cool : hate de l'essayer. 

Est-il possible de simplifier les termes techniques comme `bec d'oiseau` ?

2019-11-21 23:30 UTC, Antoine38660 commented on content/recipes/boudoirs/index.md
> +- Monter les blancs en neige (facile avec un fouet électrique), s'arrêter lorsque l'on obtient un bec d'oiseau quand vous retirez le fouet.
Bec d'oiseau ? Quésaco ?

2019-11-21 23:32 UTC, merged

2019-11-21 23:32 UTC, Antoine38660 commented
J'ai mergé, car on a besoin de contenu pour faire venir la communauté !

2019-11-22 08:58 UTC, Mesh33 commented on content/recipes/boudoirs/index.md
> +- Monter les blancs en neige (facile avec un fouet électrique), s'arrêter lorsque l'on obtient un bec d'oiseau quand vous retirez le fouet.
J'aurais voulu inclure une image avec l'étape... J'en ai une

2019-11-22 11:17 UTC, Antoine38660 commented on content/recipes/boudoirs/index.md
> +- Monter les blancs en neige (facile avec un fouet électrique), s'arrêter lorsque l'on obtient un bec d'oiseau quand vous retirez le fouet.
Hum, a réflechir pour une feature